global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['host.docker.internal:3000'] # kalau jalan di Docker
        # atau langsung 'localhost:3000'
      # - targets: ['localhost:3000'] # kalau jalan di local